### ISSUE TITLE
Minor comments...

### ISSUE THREAD

**Issue by htoyryla** [eps696/SDfu#1]
Looks like examples refer to inpainting models which are not downloaded by the download.py script (commented out). I removed the commenting and they seem to download (and work) ok.

Installing xformers as instructed did not work in practice (resulted in cpu only version) while pip install xformers  works ok.
(A bit unsure whether "Install CUDA11.8" means install from NVIDIA into /usr/local/, I did not as I prefer a conda-only install and it appears to work anyway).

**Comment by eps696** [comment]
thanks for noticing these [and sorry for leaving readme in the obsolete state after the recent update].
i uncommented depth model again for now - until i extend controlnet examples which should effectively replace it.
Also added Windows mention for CUDA setup [as I didn't really test it on other platforms, sorry for that].

**Comment by eps696** [comment]
i believe recent update fixed this issue (hopefully not bringing new ones), so closing it for now.
