### ISSUE TITLE
Can't get longanimatediff to work

### ISSUE THREAD

**Issue by glennamarshall** [eps696/SDfu#5]
I tried to use the longanimatediff model from here,
https://huggingface.co/Lightricks/LongAnimateDiff

but an error says the config.json isn't the right format

**Comment by eps696** [comment]
please use this script (the first one) to convert those models to the diffusers format (which is used in my repo)
https://github.com/huggingface/diffusers/issues/6248#issuecomment-1968442506

you should have a directory with two files: `config.json` and `diffusion_pytorch_model.safetensors` to load

**Comment by glennamarshall** [comment]
not sure if i'm doing it right - but i get this error when running your script

(SD) C:\Users\ga_ma\Desktop\SDfu\SDfu\SDfu\models\anima>python convert.py --ckpt_path lt_long_mm_16_64_frames_v1.1.ckpt --output_path long64.safetensors --motion_max_seq_length 64
C:\Users\ga_ma\AppData\Roaming\Python\Python310\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\ga_ma\AppData\Roaming\Python\Python310\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\ga_ma\AppData\Roaming\Python\Python310\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\ga_ma\pinokio\bin\miniconda\envs\SD\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\ga_ma\pinokio\bin\miniconda\envs\SD\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'

**Comment by eps696** [comment]
is it complete error log? 
`triton` module is absent on windows, that's normal, yet it should only report that, not stopping further script completion. 
what versions do you use now btw? (transformers, diffusers, xformers, pytorch, etc)

**Comment by glennamarshall** [comment]
Hi,
I know about Triton not being a problem. I'm using versions of libs that you recommended, but maybe I should use the exact versions of everything you have if you don't have any problems.

**Comment by eps696** [comment]
maybe. that error looks like xformers thinks that you do have triton installed and doesn't offer a usual workaround.
upd: try fixing versions of pytorch + xformers combo first

**Comment by glennamarshall** [comment]
So I need a different version of xformers? Which do you have?
Or if you have a converted model you could upload to somewhere, I could use that and not have to convert it myself.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eps696** [comment]
my setup: cuda 11.8, python 3.9 (3.10 should also work), pytorch 2.0.1+cu118, torchvision 0.15.2+cu118, xformers 0.0.20.
alas i don't have 64-frames model converted as it had caused OOMs even on 3090

**Comment by glennamarshall** [comment]
Many thanks for your help, will try this tomorrow!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by glennamarshall** [comment]
managed to convert the model with your lib versions - thx!

**Comment by glennamarshall** [comment]
closing
