### ISSUE TITLE
SDXL not working

### ISSUE THREAD

**Issue by stavrosdidakis** [eps696/SDfu#6]
I am using the SDXL mode and it is stuck - does not process the image, see terminal window response:

```
python src/sdxl.py -v -t prompts.txt --size 1280-768 -fs 5 -lb 0.8
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:01<00:00,  4.95it/s]
 sd xl .. 50 .. 7.5 .. 1.0 .. 22559
[                                                  ] 0/3
Start...
```

FYI, the image is processed in SD1.5 mode as normal

**Comment by eps696** [comment]
did you try waiting a bit longer? the response looks normal.
extra techniques (latent blending, ip adapter, animatedif) take some time to load (especially with sdxl), it's not as momentary as with a base model

**Comment by eps696** [comment]
supposed to be solved, closed for inactivity
