### ISSUE TITLE
What settings/steps have you implemented for your examples? 

### ISSUE THREAD

**Issue by arturovallemacias** [eps696/SDfu#9]
i made to work your repo,  but i dont get the smooth transitions you have in your examples on twitter,  which steps did you use or which .py file are you executing for such transitions?

**Comment by eps696** [comment]
you may check my recent stream with few such advices https://www.youtube.com/watch?v=4Y2MOE-PeDU
some used options: `-m 15drm -imr 3DPIX -imw 0.2 -ar -ad anima/long32 -sag 0.5 -sm ddpm` 
[3DPIX is a folder with some abstract 3d imagery]

**Comment by arturovallemacias** [comment]
> you may check my recent stream with few such advices https://www.youtube.com/watch?v=4Y2MOE-PeDU some used options: `-m 15drm -imr 3DPIX -imw 0.2 -ar -ad anima/long32 -sag 0.5 -sm ddpm` [3DPIX is a folder with some abstract 3d imagery]

 it works, but the output looks like the frame rate is increased,  it looks like in fasttrack,  how you do resolve that?  which parameter in args controls the framerate speed?

**Comment by eps696** [comment]
use FILM from google for slowing down x2
https://github.com/google-research/frame-interpolation

**Comment by eps696** [comment]
closed for inactivity
